"""APEX 69.10.14 — canonical gamma evidence identity and transition provenance.

This module remains the single observational gamma transition store. 69.10.14
extends the existing ``gamma_observational_snapshots`` table with deterministic
canonical identity, bounded provenance, freshness/continuity metadata and
read-only decision-time retrieval. It does not create trading authority.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import json
import math
import os
import sqlite3
import threading
from decimal import Decimal, InvalidOperation, ROUND_HALF_EVEN
from typing import Any, Dict, Mapping, Optional
from zoneinfo import ZoneInfo

from .canonical_persistence import connect

VERSION = "69.10.14"
SCHEMA_VERSION = "apex.gamma_transition.v3"
IDENTITY_SCHEMA_VERSION = "apex.gamma_snapshot_identity.v1"
MAX_STALE_SECONDS = 900
_ET = ZoneInfo("America/New_York")

_RUNTIME_LOCK = threading.RLock()
_RUNTIME: Dict[str, int] = {
    "gamma_snapshots_received": 0,
    "gamma_snapshots_created": 0,
    "gamma_snapshots_deduplicated": 0,
    "gamma_stale_events": 0,
    "gamma_gap_events": 0,
    "gamma_out_of_order_events": 0,
    "gamma_decisions_linked": 0,
    "gamma_decisions_missing_linkage": 0,
    "gamma_reconstructed_evidence_events": 0,
}


def _f(v: Any) -> Optional[float]:
    try:
        x = float(v)
        return x if math.isfinite(x) else None
    except (TypeError, ValueError):
        return None


def _parse(v: Any) -> Optional[dt.datetime]:
    if v in (None, ""):
        return None
    try:
        out = dt.datetime.fromisoformat(str(v).replace("Z", "+00:00"))
        if out.tzinfo is None:
            out = out.replace(tzinfo=dt.timezone.utc)
        return out.astimezone(dt.timezone.utc)
    except Exception:
        return None


def _iso(v: Any = None) -> str:
    parsed = _parse(v)
    return (parsed or dt.datetime.now(dt.timezone.utc)).isoformat()


def _db_path() -> str:
    return os.getenv("DB_PATH", "apex_tracking.db")


def _session_date(value: Any) -> str:
    parsed = _parse(value) or dt.datetime.now(dt.timezone.utc)
    return parsed.astimezone(_ET).date().isoformat()


def _env_seconds(source: str, suffix: str, default: int) -> int:
    source_key = "".join(ch if ch.isalnum() else "_" for ch in str(source or "").upper()).strip("_")
    keys = [f"APEX_GAMMA_{source_key}_{suffix}" if source_key else "", f"APEX_GAMMA_{suffix}"]
    for key in keys:
        if not key:
            continue
        try:
            return max(1, int(float(os.getenv(key, ""))))
        except (TypeError, ValueError):
            pass
    return int(default)


def _canonical_number(value: Any) -> Optional[str]:
    """Stable numeric text used only by identity material.

    Eight decimal places is well below the precision of the current provider-
    grounded gamma fields while eliminating binary floating serialization noise.
    """
    if value is None:
        return None
    try:
        d = Decimal(str(value))
        if not d.is_finite():
            return None
        q = d.quantize(Decimal("0.00000001"), rounding=ROUND_HALF_EVEN)
        text = format(q, "f").rstrip("0").rstrip(".")
        return text or "0"
    except (InvalidOperation, ValueError, TypeError):
        return None


def _canonical_text(value: Any) -> Optional[str]:
    if value in (None, ""):
        return None
    return str(value).strip()


def _provider_timestamp(gamma: Mapping[str, Any], gamma_path: Mapping[str, Any]) -> tuple[Optional[str], str]:
    """Return only timestamps explicitly represented as provider/source time.

    ``gamma_path.source_snapshot_at`` is currently generated by APEX while parsing
    the provider response. It is preserved in the compatibility source_timestamp
    column but is not mislabeled as provider-supplied provenance.
    """
    candidates = (
        gamma.get("provider_source_timestamp"),
        gamma.get("provider_timestamp"),
        gamma.get("source_timestamp"),
        gamma_path.get("provider_source_timestamp"),
        gamma_path.get("provider_timestamp"),
    )
    for value in candidates:
        parsed = _parse(value)
        if parsed is not None:
            return parsed.isoformat(), "PROVIDER_SUPPLIED"
    return None, "UNAVAILABLE"


def canonical_identity_basis(snapshot: Mapping[str, Any]) -> Dict[str, Any]:
    """Economically meaningful, deterministic identity material.

    Scanner receive/persist times are intentionally excluded. Provider observation
    identity/time is authoritative when supplied. When the provider supplies neither,
    APEX cannot prove that two unchanged polls are the *same source observation*, so
    the APEX observation timestamp becomes an explicit fallback identity component.
    This avoids false deduplication while still making exact replay/restart of a
    recorded observation deterministic.
    """
    provider_observation_id = _canonical_text(snapshot.get("provider_observation_id"))
    provider_source_timestamp = _canonical_text(snapshot.get("provider_source_timestamp"))
    return {
        "schema_version": IDENTITY_SCHEMA_VERSION,
        "ticker": str(snapshot.get("ticker") or "SPX").upper(),
        "source": str(snapshot.get("source") or "UNKNOWN").upper(),
        "provider_observation_id": provider_observation_id,
        "provider_source_timestamp": provider_source_timestamp,
        "apex_observed_at_fallback": (
            None if provider_observation_id or provider_source_timestamp
            else _canonical_text(snapshot.get("observed_at"))
        ),
        "path_version": _canonical_text(snapshot.get("path_version")),
        "level_version": _canonical_text(snapshot.get("level_version")),
        "gamma_regime": _canonical_text(snapshot.get("gamma_regime")),
        "net_gex": _canonical_number(snapshot.get("net_gex")),
        "net_gamma_ratio": _canonical_number(snapshot.get("net_gamma_ratio")),
        "gex_score": _canonical_number(snapshot.get("gex_score")),
        "gamma_flip": _canonical_number(snapshot.get("gamma_flip")),
        "zero_dte_share": _canonical_number(snapshot.get("zero_dte_share")),
        "zero_one_dte_share": _canonical_number(snapshot.get("zero_one_dte_share")),
        "weekly_gamma_share": _canonical_number(snapshot.get("weekly_gamma_share")),
        "durability": _canonical_text(snapshot.get("durability")),
        "capacity_ratio": _canonical_number(snapshot.get("capacity_ratio")),
        "term_alignment": snapshot.get("term_alignment"),
        "term_divergence": snapshot.get("term_divergence"),
    }


def canonical_gamma_snapshot_id(snapshot: Mapping[str, Any]) -> str:
    material = json.dumps(
        canonical_identity_basis(snapshot), sort_keys=True, separators=(",", ":"), ensure_ascii=True
    ).encode("utf-8")
    return "g_" + hashlib.sha256(material).hexdigest()[:32]


def _column_names(conn: sqlite3.Connection, table: str) -> set[str]:
    return {str(row[1]) for row in conn.execute(f"PRAGMA table_info({table})")}


def init_db(path: Optional[str] = None) -> bool:
    """Idempotently initialize/upgrade the existing canonical gamma snapshot table."""
    try:
        with connect(path or _db_path(), timeout=10) as c:
            c.execute(
                """CREATE TABLE IF NOT EXISTS gamma_observational_snapshots (
                id INTEGER PRIMARY KEY AUTOINCREMENT, ticker TEXT NOT NULL,
                observed_at TEXT NOT NULL, source_timestamp TEXT, source TEXT,
                path_version TEXT, net_gex REAL, gamma_flip REAL,
                zero_dte_share REAL, zero_one_dte_share REAL, weekly_gamma_share REAL,
                durability TEXT, capacity_ratio REAL, snapshot_json TEXT NOT NULL)"""
            )
            existing = _column_names(c, "gamma_observational_snapshots")
            additions = (
                ("canonical_gamma_snapshot_id", "TEXT"),
                ("session_date", "TEXT"),
                ("received_at", "TEXT"),
                ("persisted_at", "TEXT"),
                ("provider_source_timestamp", "TEXT"),
                ("source_timestamp_provenance", "TEXT"),
                ("provider_observation_id", "TEXT"),
                ("level_version", "TEXT"),
                ("gamma_regime", "TEXT"),
                ("net_gamma_ratio", "REAL"),
                ("gex_score", "REAL"),
                ("freshness_state", "TEXT"),
                ("continuity_state", "TEXT"),
                ("sequence_state", "TEXT"),
                ("provenance_class", "TEXT"),
                ("session_context_state", "TEXT"),
                ("replay_backfill_status", "TEXT"),
                ("snapshot_age_seconds", "REAL"),
                ("is_current_authority", "INTEGER NOT NULL DEFAULT 1"),
                ("term_regime_divergence_available", "INTEGER NOT NULL DEFAULT 0"),
                ("term_alignment", "INTEGER"),
                ("term_divergence", "INTEGER"),
                ("lineage_json", "TEXT"),
            )
            for name, decl in additions:
                if name not in existing:
                    c.execute(f"ALTER TABLE gamma_observational_snapshots ADD COLUMN {name} {decl}")
            c.execute(
                "CREATE INDEX IF NOT EXISTS idx_gamma_obs_ticker_time "
                "ON gamma_observational_snapshots(ticker, observed_at)"
            )
            c.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS idx_gamma_obs_canonical_identity "
                "ON gamma_observational_snapshots(canonical_gamma_snapshot_id) "
                "WHERE canonical_gamma_snapshot_id IS NOT NULL"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS idx_gamma_obs_session_time "
                "ON gamma_observational_snapshots(session_date, ticker, observed_at)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS idx_gamma_obs_source_time "
                "ON gamma_observational_snapshots(source, provider_source_timestamp)"
            )
            c.commit()
        return True
    except Exception:
        return False


def snapshot_from_gamma(
    gamma: Mapping[str, Any], *, ticker: str = "SPX", source: str = "QUANTDATA",
    observed_at: Optional[str] = None, received_at: Optional[str] = None,
    provider_observation_id: Optional[str] = None, provenance_class: str = "LIVE_OBSERVED",
    replay_backfill_status: str = "NONE",
) -> Dict[str, Any]:
    gp = gamma.get("gamma_path") if isinstance(gamma.get("gamma_path"), Mapping) else {}
    gt = gamma.get("gamma_term_structure") if isinstance(gamma.get("gamma_term_structure"), Mapping) else {}
    mc = gt.get("maturity_concentration") if isinstance(gt.get("maturity_concentration"), Mapping) else {}
    provider_ts, provider_ts_basis = _provider_timestamp(gamma, gp)
    observed = _iso(observed_at)
    received = _iso(received_at or observed)
    # Compatibility source timestamp: historically this was gamma_path.source_snapshot_at,
    # which is an APEX parse timestamp. Preserve it, but classify its provenance honestly.
    compat_source_ts = gp.get("source_snapshot_at") or provider_ts
    compat_basis = provider_ts_basis if provider_ts else ("APEX_DERIVED_PARSE_TIME" if compat_source_ts else "UNAVAILABLE")
    expirations = gt.get("expirations") if isinstance(gt.get("expirations"), list) else []
    signed_rows = [r for r in expirations if isinstance(r, Mapping) and _f(r.get("net_gamma_ratio")) is not None]
    term_available = bool(signed_rows)
    snap: Dict[str, Any] = {
        "ticker": str(ticker or "SPX").upper(),
        "session_date": _session_date(observed),
        "observed_at": observed,
        "received_at": received,
        "source_timestamp": _iso(compat_source_ts) if _parse(compat_source_ts) else None,
        "provider_source_timestamp": provider_ts,
        "source_timestamp_provenance": compat_basis,
        "source": str(source or "UNKNOWN").upper(),
        "provider_observation_id": provider_observation_id or gamma.get("provider_observation_id"),
        "path_version": gp.get("path_version"),
        "level_version": gp.get("level_version"),
        "gamma_regime": gp.get("current_regime") or gamma.get("gex_status"),
        "net_gex": _f(gamma.get("net_gex")),
        "net_gamma_ratio": _f(gamma.get("net_gamma_ratio")),
        "gex_score": _f(gamma.get("gex_score")),
        "gamma_flip": _f(gamma.get("active_gamma_flip") or gamma.get("zero_gamma")),
        "zero_dte_share": _f(mc.get("zero_dte_gamma_share")),
        "zero_one_dte_share": _f(mc.get("zero_one_dte_gamma_share")),
        "weekly_gamma_share": _f(mc.get("seven_dte_gamma_share")),
        "durability": mc.get("structure_durability"),
        "capacity_ratio": _f(gamma.get("capacity_ratio")),
        "term_regime_divergence_available": term_available,
        "term_alignment": gt.get("term_alignment") if term_available else None,
        "term_divergence": gt.get("term_divergence") if term_available else None,
        "provenance_class": str(provenance_class or "UNKNOWN").upper(),
        "replay_backfill_status": str(replay_backfill_status or "NONE").upper(),
    }
    snap["canonical_gamma_snapshot_id"] = canonical_gamma_snapshot_id(snap)
    snap["identity_schema_version"] = IDENTITY_SCHEMA_VERSION
    return snap


def _market_closed(market_state: Any) -> bool:
    text = str(market_state or "").upper()
    return text in {"CLOSED", "MARKET_CLOSED", "AFTER_HOURS", "WEEKEND", "HOLIDAY"}


def freshness_for_snapshot(
    snapshot: Mapping[str, Any], *, reference_at: Any = None, market_state: Any = None
) -> Dict[str, Any]:
    reference = _parse(reference_at) or dt.datetime.now(dt.timezone.utc)
    provider_ts = _parse(snapshot.get("provider_source_timestamp"))
    observed = _parse(snapshot.get("observed_at"))
    basis_dt = provider_ts or observed
    if basis_dt is None:
        return {
            "freshness_state": "UNKNOWN", "snapshot_age_seconds": None,
            "freshness_basis": "UNAVAILABLE", "session_context_state": "UNKNOWN",
        }
    raw_age = (reference - basis_dt).total_seconds()
    if raw_age < 0:
        return {
            "freshness_state": "UNKNOWN", "snapshot_age_seconds": round(raw_age, 3),
            "freshness_basis": "PROVIDER_SOURCE_TIMESTAMP" if provider_ts else "APEX_OBSERVED_AT",
            "session_context_state": "PRIOR_SESSION_CONTEXT" if _market_closed(market_state) else "LIVE_SESSION_CONTEXT",
            "temporal_order_valid": False,
        }
    age = raw_age
    source = str(snapshot.get("source") or "UNKNOWN")
    fresh_seconds = _env_seconds(source, "FRESH_SECONDS", 120)
    aging_seconds = max(fresh_seconds, _env_seconds(source, "AGING_SECONDS", 300))
    if age <= fresh_seconds:
        state = "FRESH"
    elif age <= aging_seconds:
        state = "AGING"
    else:
        state = "STALE"
    session_context = "PRIOR_SESSION_CONTEXT" if _market_closed(market_state) else "LIVE_SESSION_CONTEXT"
    return {
        "freshness_state": state,
        "snapshot_age_seconds": round(age, 3),
        "freshness_basis": "PROVIDER_SOURCE_TIMESTAMP" if provider_ts else "APEX_OBSERVED_AT",
        "fresh_seconds": fresh_seconds,
        "aging_seconds": aging_seconds,
        "session_context_state": session_context,
        "temporal_order_valid": True,
    }


def _prior(path: str, ticker: str, observed: dt.datetime, minutes: int) -> Optional[Dict[str, Any]]:
    target = observed - dt.timedelta(minutes=minutes)
    with connect(path, timeout=10) as c:
        c.row_factory = sqlite3.Row
        r = c.execute(
            "SELECT * FROM gamma_observational_snapshots "
            "WHERE ticker=? AND observed_at<=? ORDER BY observed_at DESC LIMIT 1",
            (ticker, target.isoformat()),
        ).fetchone()
    return dict(r) if r else None


def _delta(cur: Mapping[str, Any], prev: Optional[Mapping[str, Any]], key: str, observed: dt.datetime, minutes: int) -> Optional[float]:
    if not prev:
        return None
    pt = _parse(prev.get("observed_at")); a, b = _f(cur.get(key)), _f(prev.get(key))
    if pt is None or a is None or b is None:
        return None
    age = (observed - pt).total_seconds()
    lag_tolerance = 60 if minutes <= 1 else MAX_STALE_SECONDS
    if age < minutes * 60 or age > minutes * 60 + lag_tolerance:
        return None
    return round(a - b, 6)


def _normalized_change(cur: Mapping[str, Any], prev: Optional[Mapping[str, Any]], key: str,
                       observed: dt.datetime, minutes: int) -> Optional[float]:
    d = _delta(cur, prev, key, observed, minutes)
    prior = _f(prev.get(key)) if prev else None
    if d is None or prior is None or abs(prior) < 1e-9:
        return None
    return round(d / abs(prior), 6)


def compute_transition(current: Mapping[str, Any], *, db_path: Optional[str] = None) -> Dict[str, Any]:
    path = db_path or _db_path(); observed = _parse(current.get("observed_at"))
    base = {
        "status": "UNAVAILABLE", "transition_state": "UNAVAILABLE",
        "net_gex_change_1m": None, "net_gex_change_5m": None, "net_gex_change_15m": None, "net_gex_change_30m": None,
        "net_gex_transition_ratio_1m": None, "net_gex_transition_ratio_5m": None,
        "net_gex_transition_ratio_15m": None, "net_gex_transition_ratio_30m": None,
        "transition_magnitude_ratio": None, "gamma_capacity_change_15m": None,
        "gamma_flip_change": None, "gamma_flip_velocity": None, "zero_dte_share_change": None, "zero_one_dte_share_change": None,
        "weekly_gamma_share_change": None, "durability_change": None, "gamma_path_transition": None,
        "transition_lineage": [], "schema_version": SCHEMA_VERSION,
        "behavioral_authority": False, "execution_authority": False,
        "automatic_calibration_activation": False, "production_effect": "NONE",
    }
    if observed is None:
        return base
    try:
        p1, p5, p15, p30 = (_prior(path, str(current.get("ticker") or "SPX"), observed, m) for m in (1, 5, 15, 30))
    except Exception:
        return base
    d1 = _delta(current, p1, "net_gex", observed, 1); d5 = _delta(current, p5, "net_gex", observed, 5)
    d15 = _delta(current, p15, "net_gex", observed, 15); d30 = _delta(current, p30, "net_gex", observed, 30)
    r1 = _normalized_change(current, p1, "net_gex", observed, 1); r5 = _normalized_change(current, p5, "net_gex", observed, 5)
    r15 = _normalized_change(current, p15, "net_gex", observed, 15); r30 = _normalized_change(current, p30, "net_gex", observed, 30)
    flip15 = _delta(current, p15, "gamma_flip", observed, 15)
    capacity15 = _delta(current, p15, "capacity_ratio", observed, 15)
    z15 = _delta(current, p15, "zero_dte_share", observed, 15); zo15 = _delta(current, p15, "zero_one_dte_share", observed, 15)
    w15 = _delta(current, p15, "weekly_gamma_share", observed, 15)
    available = [x for x in (d1, d5, d15, d30, flip15, z15, zo15, w15, capacity15) if x is not None]
    lineage = []
    for horizon, row in ((1, p1), (5, p5), (15, p15), (30, p30)):
        if row:
            lineage.append({
                "horizon_minutes": horizon,
                "canonical_gamma_snapshot_id": row.get("canonical_gamma_snapshot_id"),
                "observed_at": row.get("observed_at"),
            })
    if not available:
        return {**base, "status": "COLLECTING", "transition_state": "INSUFFICIENT_HISTORY", "transition_lineage": lineage}
    rapid = (r1 is not None and abs(r1) >= .20) or (r5 is not None and abs(r5) >= .30)
    if rapid:
        state = "RAPID_TRANSITION"
    elif r15 is not None and r15 >= .10:
        state = "STRENGTHENING"
    elif r15 is not None and r15 <= -.10:
        state = "WEAKENING"
    else:
        state = "STABLE"
    prev = p15 or p5 or p1 or p30
    ratios = [abs(x) for x in (r1, r5, r15, r30) if x is not None]
    return {
        **base, "status": "AVAILABLE", "transition_state": state,
        "net_gex_change_1m": d1, "net_gex_change_5m": d5, "net_gex_change_15m": d15, "net_gex_change_30m": d30,
        "net_gex_transition_ratio_1m": r1, "net_gex_transition_ratio_5m": r5,
        "net_gex_transition_ratio_15m": r15, "net_gex_transition_ratio_30m": r30,
        "transition_magnitude_ratio": round(max(ratios), 6) if ratios else None,
        "gamma_capacity_change_15m": capacity15,
        "gamma_flip_change": flip15, "gamma_flip_velocity": None if flip15 is None else round(flip15 / 15.0, 6),
        "zero_dte_share_change": z15, "zero_one_dte_share_change": zo15, "weekly_gamma_share_change": w15,
        "durability_change": None if not prev else f"{prev.get('durability') or 'UNKNOWN'}->{current.get('durability') or 'UNKNOWN'}",
        "gamma_path_transition": None if not prev else f"{prev.get('path_version') or 'UNKNOWN'}->{current.get('path_version') or 'UNKNOWN'}",
        "transition_lineage": lineage,
    }


def _continuity_for_new(path: str, snap: Mapping[str, Any]) -> Dict[str, Any]:
    observed = _parse(snap.get("observed_at"))
    if observed is None:
        return {"continuity_state": "UNKNOWN", "sequence_state": "MALFORMED_TIMESTAMP", "is_current_authority": False, "gap_seconds": None}
    provenance = str(snap.get("provenance_class") or "UNKNOWN").upper()
    replay_status = str(snap.get("replay_backfill_status") or "NONE").upper()
    if provenance in {"REPLAYED", "BACKFILLED", "RECONSTRUCTED"} or replay_status not in {"", "NONE", "LIVE"}:
        return {"continuity_state": "BACKFILLED", "sequence_state": "HISTORICAL_INSERT", "is_current_authority": False, "gap_seconds": None}
    try:
        with connect(path, timeout=10) as c:
            c.row_factory = sqlite3.Row
            row = c.execute(
                "SELECT * FROM gamma_observational_snapshots WHERE ticker=? "
                "AND canonical_gamma_snapshot_id IS NOT NULL "
                "AND provenance_class IN ('LIVE_OBSERVED','DECISION_TIME_CAPTURED') "
                "ORDER BY observed_at DESC LIMIT 1",
                (str(snap.get("ticker") or "SPX"),),
            ).fetchone()
    except Exception:
        row = None
    if not row:
        return {"continuity_state": "UNKNOWN", "sequence_state": "FIRST_OBSERVATION", "is_current_authority": True, "gap_seconds": None}
    prev = dict(row); prev_dt = _parse(prev.get("observed_at"))
    if prev_dt is None:
        return {"continuity_state": "UNKNOWN", "sequence_state": "PRIOR_TIME_UNKNOWN", "is_current_authority": True, "gap_seconds": None}
    delta = (observed - prev_dt).total_seconds()
    if delta < 0:
        return {"continuity_state": "GAPPED", "sequence_state": "OUT_OF_ORDER", "is_current_authority": False, "gap_seconds": round(abs(delta), 3)}
    cadence = _env_seconds(str(snap.get("source") or "UNKNOWN"), "EXPECTED_CADENCE_SECONDS", 60)
    gap_threshold = max(cadence * 2.5, float(_env_seconds(str(snap.get("source") or "UNKNOWN"), "GAP_SECONDS", 180)))
    if delta > gap_threshold:
        return {"continuity_state": "GAPPED", "sequence_state": "FORWARD_GAP", "is_current_authority": True, "gap_seconds": round(delta, 3)}
    if str(prev.get("continuity_state") or "").upper() == "GAPPED":
        return {"continuity_state": "RECOVERED", "sequence_state": "IN_ORDER", "is_current_authority": True, "gap_seconds": round(delta, 3)}
    return {"continuity_state": "CONTINUOUS", "sequence_state": "IN_ORDER", "is_current_authority": True, "gap_seconds": round(delta, 3)}


def _row_to_snapshot(row: Mapping[str, Any]) -> Dict[str, Any]:
    out = dict(row)
    try:
        payload = json.loads(out.get("snapshot_json") or "{}")
    except Exception:
        payload = {}
    # Column truth wins over the bounded JSON compatibility payload.
    merged = {**payload, **out}
    try:
        merged["lineage"] = json.loads(out.get("lineage_json") or "[]")
    except Exception:
        merged["lineage"] = []
    return merged


def get_snapshot_by_id(snapshot_id: str, *, db_path: Optional[str] = None) -> Optional[Dict[str, Any]]:
    if not snapshot_id:
        return None
    path = db_path or _db_path()
    if not init_db(path):
        return None
    try:
        with connect(path, timeout=10) as c:
            c.row_factory = sqlite3.Row
            row = c.execute(
                "SELECT * FROM gamma_observational_snapshots WHERE canonical_gamma_snapshot_id=? LIMIT 1",
                (str(snapshot_id),),
            ).fetchone()
        return _row_to_snapshot(dict(row)) if row else None
    except Exception:
        return None


def current_gamma_integrity(*, ticker: str = "SPX", db_path: Optional[str] = None,
                            reference_at: Any = None, market_state: Any = None) -> Dict[str, Any]:
    path = db_path or _db_path()
    if not init_db(path):
        return {"status": "UNAVAILABLE", "gamma_evidence_health": "UNAVAILABLE", "execution_authority": False}
    try:
        with connect(path, timeout=10) as c:
            c.row_factory = sqlite3.Row
            row = c.execute(
                "SELECT * FROM gamma_observational_snapshots WHERE ticker=? "
                "AND canonical_gamma_snapshot_id IS NOT NULL AND is_current_authority=1 "
                "ORDER BY observed_at DESC LIMIT 1", (str(ticker).upper(),),
            ).fetchone()
    except Exception:
        row = None
    if not row:
        return {"status": "WAITING_FOR_LIVE_GAMMA", "gamma_evidence_health": "UNKNOWN", "execution_authority": False}
    snap = _row_to_snapshot(dict(row)); fresh = freshness_for_snapshot(snap, reference_at=reference_at, market_state=market_state)
    if _market_closed(market_state):
        health = "PRIOR_SESSION_CONTEXT"
    else:
        health = "HEALTHY" if fresh["freshness_state"] == "FRESH" and snap.get("continuity_state") in {"CONTINUOUS", "RECOVERED", "UNKNOWN"} else "DEGRADED"
    return {
        "status": "AVAILABLE", "gamma_evidence_health": health,
        "canonical_gamma_snapshot_id": snap.get("canonical_gamma_snapshot_id"),
        "ticker": snap.get("ticker"), "provider": snap.get("source"),
        "observed_at": snap.get("observed_at"), "provider_source_timestamp": snap.get("provider_source_timestamp"),
        "continuity_state": snap.get("continuity_state"), "sequence_state": snap.get("sequence_state"),
        "provenance_class": snap.get("provenance_class"), **fresh,
        "gamma_regime": snap.get("gamma_regime"), "net_gex": snap.get("net_gex"),
        "gamma_flip": snap.get("gamma_flip"), "durability": snap.get("durability"),
        "zero_dte_share": snap.get("zero_dte_share"), "zero_one_dte_share": snap.get("zero_one_dte_share"),
        "weekly_gamma_share": snap.get("weekly_gamma_share"), "term_regime_divergence_available": bool(snap.get("term_regime_divergence_available")),
        "execution_authority": False, "behavioral_authority": False, "production_effect": "NONE",
    }


def decision_time_gamma_evidence(snapshot_id: str, *, decision_time: Any,
                                 market_state: Any = None, db_path: Optional[str] = None) -> Dict[str, Any]:
    """Return a bounded frozen view of the exact canonical gamma observation.

    This function never substitutes the latest snapshot when ``snapshot_id`` is
    missing. Legacy/missing linkage is explicit, preventing temporal leakage.
    """
    snap = get_snapshot_by_id(snapshot_id, db_path=db_path)
    if not snap:
        with _RUNTIME_LOCK:
            _RUNTIME["gamma_decisions_missing_linkage"] += 1
        return {
            "linkage_status": "LEGACY_OR_UNKNOWN", "canonical_gamma_snapshot_id": snapshot_id or None,
            "freshness_state": "UNKNOWN", "continuity_state": "UNKNOWN", "provenance_class": "UNKNOWN",
            "gamma_snapshot_age_seconds": None, "execution_authority": False, "behavioral_authority": False,
        }
    fresh = freshness_for_snapshot(snap, reference_at=decision_time, market_state=market_state)
    decision_dt = _parse(decision_time)
    received_dt = _parse(snap.get("received_at"))
    available_at_decision = bool(decision_dt is not None and (received_dt is None or received_dt <= decision_dt))
    if not available_at_decision:
        fresh = {**fresh, "freshness_state": "UNKNOWN", "temporal_order_valid": False}
    with _RUNTIME_LOCK:
        _RUNTIME["gamma_decisions_linked"] += 1
        if str(snap.get("provenance_class") or "").upper() in {"RECONSTRUCTED", "REPLAYED", "BACKFILLED"}:
            _RUNTIME["gamma_reconstructed_evidence_events"] += 1
    return {
        "linkage_status": "LINKED",
        "canonical_gamma_snapshot_id": snap.get("canonical_gamma_snapshot_id"),
        "gamma_observation_timestamp": snap.get("observed_at"),
        "gamma_received_at": snap.get("received_at"),
        "gamma_provider_source_timestamp": snap.get("provider_source_timestamp"),
        "gamma_source_timestamp_provenance": snap.get("source_timestamp_provenance"),
        "gamma_source": snap.get("source"),
        "gamma_snapshot_age_seconds": fresh.get("snapshot_age_seconds"),
        "freshness_state": fresh.get("freshness_state"),
        "freshness_basis": fresh.get("freshness_basis"),
        "session_context_state": fresh.get("session_context_state"),
        "temporal_order_valid": fresh.get("temporal_order_valid"),
        "available_at_decision": available_at_decision,
        "continuity_state": snap.get("continuity_state") or "UNKNOWN",
        "sequence_state": snap.get("sequence_state") or "UNKNOWN",
        "provenance_class": snap.get("provenance_class") or "UNKNOWN",
        "gamma_regime": snap.get("gamma_regime"), "net_gex": snap.get("net_gex"),
        "gamma_flip": snap.get("gamma_flip"), "capacity_ratio": snap.get("capacity_ratio"),
        "durability": snap.get("durability"), "zero_dte_share": snap.get("zero_dte_share"),
        "zero_one_dte_share": snap.get("zero_one_dte_share"), "weekly_gamma_share": snap.get("weekly_gamma_share"),
        "path_version": snap.get("path_version"), "level_version": snap.get("level_version"),
        "term_regime_divergence_available": bool(snap.get("term_regime_divergence_available")),
        "term_alignment": snap.get("term_alignment"), "term_divergence": snap.get("term_divergence"),
        "identity_schema_version": IDENTITY_SCHEMA_VERSION,
        "execution_authority": False, "behavioral_authority": False, "production_effect": "NONE",
    }


def metrics_snapshot() -> Dict[str, Any]:
    with _RUNTIME_LOCK:
        values = dict(_RUNTIME)
    return {**values, "schema_version": "apex.gamma_provenance_metrics.v1", "version": VERSION,
            "high_cardinality_labels": False, "execution_authority": False}


def observe_gamma_transition(
    gamma: Mapping[str, Any], *, ticker: str = "SPX", source: str = "QUANTDATA",
    observed_at: Optional[str] = None, db_path: Optional[str] = None,
    received_at: Optional[str] = None, provider_observation_id: Optional[str] = None,
    provenance_class: str = "LIVE_OBSERVED", replay_backfill_status: str = "NONE",
    market_state: Any = None,
) -> Dict[str, Any]:
    path = db_path or _db_path()
    if observed_at not in (None, "") and _parse(observed_at) is None:
        return {"status": "UNAVAILABLE", "transition_state": "MALFORMED_OBSERVATION_TIMESTAMP",
                "freshness_state": "UNKNOWN", "continuity_state": "UNKNOWN",
                "behavioral_authority": False, "execution_authority": False, "production_effect": "NONE"}
    if received_at not in (None, "") and _parse(received_at) is None:
        return {"status": "UNAVAILABLE", "transition_state": "MALFORMED_RECEIVE_TIMESTAMP",
                "freshness_state": "UNKNOWN", "continuity_state": "UNKNOWN",
                "behavioral_authority": False, "execution_authority": False, "production_effect": "NONE"}
    with _RUNTIME_LOCK:
        _RUNTIME["gamma_snapshots_received"] += 1
    if not init_db(path):
        return {"status": "UNAVAILABLE", "transition_state": "UNAVAILABLE", "execution_authority": False, "behavioral_authority": False}
    snap = snapshot_from_gamma(
        gamma, ticker=ticker, source=source, observed_at=observed_at, received_at=received_at,
        provider_observation_id=provider_observation_id, provenance_class=provenance_class,
        replay_backfill_status=replay_backfill_status,
    )
    transition = compute_transition(snap, db_path=path)
    continuity = _continuity_for_new(path, snap)
    freshness = freshness_for_snapshot(snap, reference_at=snap.get("received_at"), market_state=market_state)
    snap.update(continuity)
    snap.update({
        "freshness_state": freshness.get("freshness_state"),
        "snapshot_age_seconds": freshness.get("snapshot_age_seconds"),
        "session_context_state": freshness.get("session_context_state"),
        "persisted_at": _iso(),
    })
    lineage = transition.get("transition_lineage") if isinstance(transition.get("transition_lineage"), list) else []
    snap["lineage"] = lineage
    created = False
    try:
        with connect(path, timeout=10) as c:
            cur = c.execute(
                """INSERT OR IGNORE INTO gamma_observational_snapshots
                (canonical_gamma_snapshot_id,ticker,session_date,observed_at,received_at,persisted_at,
                 source_timestamp,provider_source_timestamp,source_timestamp_provenance,source,
                 provider_observation_id,path_version,level_version,gamma_regime,net_gex,net_gamma_ratio,
                 gex_score,gamma_flip,zero_dte_share,zero_one_dte_share,weekly_gamma_share,durability,
                 capacity_ratio,freshness_state,continuity_state,sequence_state,provenance_class,
                 session_context_state,replay_backfill_status,snapshot_age_seconds,is_current_authority,
                 term_regime_divergence_available,term_alignment,term_divergence,lineage_json,snapshot_json)
                VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    snap["canonical_gamma_snapshot_id"], snap["ticker"], snap["session_date"], snap["observed_at"],
                    snap["received_at"], snap["persisted_at"], snap.get("source_timestamp"), snap.get("provider_source_timestamp"),
                    snap.get("source_timestamp_provenance"), snap.get("source"), snap.get("provider_observation_id"),
                    snap.get("path_version"), snap.get("level_version"), snap.get("gamma_regime"), snap.get("net_gex"),
                    snap.get("net_gamma_ratio"), snap.get("gex_score"), snap.get("gamma_flip"), snap.get("zero_dte_share"),
                    snap.get("zero_one_dte_share"), snap.get("weekly_gamma_share"), snap.get("durability"), snap.get("capacity_ratio"),
                    snap.get("freshness_state"), snap.get("continuity_state"), snap.get("sequence_state"), snap.get("provenance_class"),
                    snap.get("session_context_state"), snap.get("replay_backfill_status"), snap.get("snapshot_age_seconds"),
                    int(bool(snap.get("is_current_authority"))), int(bool(snap.get("term_regime_divergence_available"))),
                    None if snap.get("term_alignment") is None else int(bool(snap.get("term_alignment"))),
                    None if snap.get("term_divergence") is None else int(bool(snap.get("term_divergence"))),
                    json.dumps(lineage, sort_keys=True, separators=(",", ":"), default=str),
                    json.dumps(snap, sort_keys=True, separators=(",", ":"), default=str),
                ),
            )
            created = cur.rowcount > 0
            c.commit()
    except Exception:
        created = False
    with _RUNTIME_LOCK:
        if created:
            _RUNTIME["gamma_snapshots_created"] += 1
        else:
            _RUNTIME["gamma_snapshots_deduplicated"] += 1
        if snap.get("freshness_state") == "STALE" and not _market_closed(market_state):
            _RUNTIME["gamma_stale_events"] += 1
        if snap.get("continuity_state") == "GAPPED":
            _RUNTIME["gamma_gap_events"] += 1
        if snap.get("sequence_state") == "OUT_OF_ORDER":
            _RUNTIME["gamma_out_of_order_events"] += 1
    # If deduplicated, surface persisted truth rather than newly derived sequence metadata.
    persisted = get_snapshot_by_id(snap["canonical_gamma_snapshot_id"], db_path=path) or snap
    integrity = {
        "canonical_gamma_snapshot_id": persisted.get("canonical_gamma_snapshot_id"),
        "gamma_observation_timestamp": persisted.get("observed_at"),
        "gamma_received_at": persisted.get("received_at"),
        "gamma_provider_source_timestamp": persisted.get("provider_source_timestamp"),
        "gamma_source_timestamp_provenance": persisted.get("source_timestamp_provenance"),
        "gamma_source": persisted.get("source"),
        "gamma_snapshot_age_seconds": persisted.get("snapshot_age_seconds"),
        "freshness_state": persisted.get("freshness_state") or "UNKNOWN",
        "continuity_state": persisted.get("continuity_state") or "UNKNOWN",
        "sequence_state": persisted.get("sequence_state") or "UNKNOWN",
        "provenance_class": persisted.get("provenance_class") or "UNKNOWN",
        "session_context_state": persisted.get("session_context_state") or "UNKNOWN",
        "snapshot_created": bool(created), "snapshot_deduplicated": not bool(created),
        "is_current_authority": bool(persisted.get("is_current_authority", True)),
        "term_regime_divergence_available": bool(persisted.get("term_regime_divergence_available")),
        "evidence_integrity_available": True,
    }
    return {**transition, **integrity, "version": VERSION, "schema_version": SCHEMA_VERSION,
            "gamma_provenance_metrics": metrics_snapshot(),
            "behavioral_authority": False, "execution_authority": False,
            "automatic_calibration_activation": False, "production_effect": "NONE"}
