"""Central APEX release identifiers used by production diagnostics."""

APEX_VERSION = "50.4.1"
MORNING_BRIEF_VERSION = "50.4.1_VALIDATION_CONSISTENCY_HOTFIX"
VALIDATION_VERSION = "50.4.1_VALIDATION_CONSISTENCY_HOTFIX"
